---
title: "Tutorial: Use Cases"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial: Use Cases}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}f
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# installed_packages <- rownames(installed.packages())
# if (!'LHTPicker' %in% installed_packages) {
#   devtools::install_github("https://github.com/d2gex/LHTPicker", dep=TRUE)
# }
# Ensure knitr does run the vignette from the same folder as interactively
knitr::opts_knit$set(root.dir = dirname(getwd()))
library(LHTpicker)
```

# 1. Fetch wanted LHTs from FishLife

## 1.1 Inputted taxa details

A csv file with the taxon names you are after and the **wanted** LHTs is required as shown below
```{r}
taxon_lhts_to_fetch <- readRDS("vignettes/data/wanted_taxon_details.rds")
head(taxon_lhts_to_fetch)
```

## 1.2 Fetching predicted LHTs
```{r}
p_lht_picker <- PredictedLHTPicker$new(FishLife::FishBase_and_Morphometrics,
                                       fishlife_context$lht_names,
                                       fishlife_context$backtransform_function_list,
                                       taxon_lhts_to_fetch)
predicted_lht_df <- p_lht_picker$pick_and_backtransform()
head(predicted_lht_df)
```
# 2 Fetch updated LHTs given new data

## 2.1 Inputted predicting taxa details
A csv file with the taxon names you are after and the **wanted-to-update** LHTs is required as shown below
```{r}
taxon_lhts_to_update <- readRDS("vignettes/data/wanted_update_taxon_details.rds")
head(taxon_lhts_to_update)
```
## 2.2 Fetching updated LHTs
```{r}

u_lht_picker <- UpdatedLHTPicker$new(
  FishLife::FishBase_and_Morphometrics,
  taxon_lhts_to_update,
  fishlife_context$updated_prefix,
  fishlife_context$transform_function_list,
  fishlife_context$backtransform_function_list,
  fishlife_context$lht_names
)
updated_lht_df <- u_lht_picker$pick_and_backtransform()
head(updated_lht_df)
```
